server:
  port: 20001
spring:
  application:
    name: cloud-server
  cloud:
    bus:
      refresh:
        enabled: true
      enabled: true
      trace:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/Wilson-He/notes     # 配置git仓库的地址
#          http://localhost:20000/test-dev.properties
          search-paths: test                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: Wilson-He                                        # git仓库的账号
          password:                                     # git仓库的密码
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/   # 注册中心eurka地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh