server:
  port: 20001
spring:
  application:
    name: cloud-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Wilson-He/notes     # 配置git仓库的地址
          search-paths: test                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: Wilson-He                                        # git仓库的账号
          password:                                     # git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/   # 注册中心eurka地址