spring:
  application:
    name: cloud-eureka
  boot:
    admin:
      client:
        url: "http://localhost:8999"
#  security:
#    user:
#      name: wilson
#      password: 111111
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8761
