server:
  port: 9000
spring:
  application:
    name: admin-server
  security:
    user:
      name: wilson
      password: 111111
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
